"""add spread column to games table

Revision ID: eeb5216a1f51
Revises: 56d1db22aeae
Create Date: 2026-03-12 09:02:49.903315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb5216a1f51'
down_revision: Union[str, None] = '56d1db22aeae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('spread', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('over_under', sa.Float(), nullable=True))
    op.drop_constraint('uq_leagues_name', 'leagues', type_='unique')
    op.drop_index('ix_leagues_name', table_name='leagues')
    op.create_index(op.f('ix_leagues_name'), 'leagues', ['name'], unique=True)
    op.drop_index('ix_participants_user_comp', table_name='participants')
    op.drop_index('ix_picks_user_comp_game', table_name='picks')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_picks_user_comp_game', 'picks', ['user_id', 'competition_id', 'game_id'], unique=True)
    op.create_index('ix_participants_user_comp', 'participants', ['user_id', 'competition_id'], unique=True)
    op.drop_index(op.f('ix_leagues_name'), table_name='leagues')
    op.create_index('ix_leagues_name', 'leagues', ['name'], unique=False)
    op.create_unique_constraint('uq_leagues_name', 'leagues', ['name'])
    op.drop_column('games', 'over_under')
    op.drop_column('games', 'spread')
    # ### end Alembic commands ###
