"""add invite_links table

Revision ID: e9a967f12abd
Revises: a1b2c3d4e5f6
Create Date: 2026-03-16 07:22:39.026438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a967f12abd'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_admin_invite', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_links_competition_id'), 'invite_links', ['competition_id'], unique=False)
    op.create_index(op.f('ix_invite_links_created_by_user_id'), 'invite_links', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_invite_links_id'), 'invite_links', ['id'], unique=False)
    op.create_index(op.f('ix_invite_links_token'), 'invite_links', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_links_token'), table_name='invite_links')
    op.drop_index(op.f('ix_invite_links_id'), table_name='invite_links')
    op.drop_index(op.f('ix_invite_links_created_by_user_id'), table_name='invite_links')
    op.drop_index(op.f('ix_invite_links_competition_id'), table_name='invite_links')
    op.drop_table('invite_links')
    # ### end Alembic commands ###
